# Generated by Django 4.2.13 on 2024-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
