# Generated by Django 4.2.13 on 2024-06-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('subtitle', models.CharField(max_length=255)),
                ('pages', models.CharField(max_length=255)),
                ('in_stock', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Bookss',
            },
        ),
    ]
